version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  mongo:
    image: mongo
    container_name: transport-company-mongo
    environment:
      MONGO_INITDB_DATABASE: invoices-transport-company
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
volumes:
  db_data: